export const cardNames: string[] = [
  "Burial from a Different Dimension",
  "Charge of the Light Brigade",
  "Infernoid Antra",
  "Infernoid Attondel",
  "Infernoid Decatron",
  "Infernoid Devyaty",
  "Infernoid Harmadik",
  "Infernoid Onuncu",
  "Infernoid Patrulea",
  "Infernoid Pirmais",
  "Infernoid Seitsemas",
  "Lyla, Lightsworn Sorceress",
  "Monster Gate",
  "One for One",
  "Raiden, Hand of the Lightsworn",
  "Reasoning",
  "Time-Space Trap Hole",
  "Torrential Tribute",
  "Upstart Goblin",
  "Void Seer"
];